import type { FixedIncomeIndexationKey, InstrumentTypeKey, InvestmentClassKey, RateConventionKey } from "./constants";

export type AssetHoldingDto = {
  id: string;
  catalogItemId: number | null;
  typeName: string;
  customTypeName: string | null;
  issuer: string;
  productName: string;
  pricingSource: "MANUAL" | "BRAPI" | "YAHOO" | "PLUGGY";
  positionSource: "MANUAL" | "PLUGGY";
  ticker: string | null;
  brapiAssetType: string | null;
  brapiSubType: string | null;
  marketExchange: string | null;
  marketQuoteType: string | null;
  marketSector: string | null;
  marketIndustry: string | null;
  currency: string;
  quantity: string;
  unitPrice: string;
  unitPriceBrl: string;
  fxRateToBrl: string | null;
  fxUpdatedAt: string | null;
  investedValue: string | null;
  averagePricePaid: string | null;
  averagePriceCoverage: number;
  currentValue: string;
  fractional: boolean;
  rateConvention: RateConventionKey | null;
  benchmark: string | null;
  rateValue: string | null;
  purchaseDate: string | null;
  maturityDate: string | null;
  logoUrl: string | null;
  priceUpdatedAt: string | null;
  providerCurrentValue: string | null;
  providerStatus: string | null;
  providerAvailable: boolean;
  transactions: Array<{
    id: string;
    description: string | null;
    type: string;
    movementType: string | null;
    quantity: string | null;
    value: string | null;
    amount: string | null;
    netAmount: string | null;
    agreedRate: string | null;
    date: string;
    tradeDate: string | null;
  }>;
  updatedAt: string;
};

export type AssetDto = {
  id: string;
  investmentClass: InvestmentClassKey;
  instrumentType: InstrumentTypeKey;
  ticker: string;
  name: string;
  fixedIncomeFamilyCode: string | null;
  fixedIncomeFamilyName: string | null;
  fixedIncomeFamilyShortCode: string | null;
  indexation: FixedIncomeIndexationKey | null;
  logoUrl: string | null;
  currency: string;
  quantity: string;
  unitPrice: string;
  nativeUnitPrice: string | null;
  fxRateToBrl: string | null;
  fxUpdatedAt: string | null;
  manualValue: string | null;
  currentValue: string;
  averagePricePaid: string | null;
  averagePriceCoverage: number;
  fractional: boolean;
  score: number;
  priceUpdatedAt: string | null;
  updatedAt: string;
  holdings: AssetHoldingDto[];
  pluggyControlled: boolean;
  needsScore: boolean;
};

export type PortfolioDto = {
  id: string;
  version: number;
  targets: Record<InvestmentClassKey, number>;
  assets: AssetDto[];
  fixedIncomeFamilies: Array<{ code: string; name: string; shortCode: string; sortOrder: number }>;
  catalog: Array<{
    id: number;
    category: string;
    name: string;
    summary: string;
    familyCode: string | null;
  }>;
  integrationReview: Array<{
    id: string;
    investmentName: string;
    institution: string;
    providerType: string;
    providerSubtype: string | null;
    balance: string;
    code: string | null;
    isin: string | null;
    value: string | null;
    quantity: string | null;
    amount: string | null;
    taxes: string | null;
    taxes2: string | null;
    amountProfit: string | null;
    amountWithdrawal: string | null;
    amountOriginal: string | null;
    lastMonthRate: string | null;
    annualRate: string | null;
    lastTwelveMonthsRate: string | null;
    currencyCode: string;
    quotaDate: string | null;
    owner: string | null;
    number: string | null;
    institutionNumber: string | null;
    insurerName: string | null;
    insurerCnpj: string | null;
    issuer: string | null;
    issuerCnpj: string | null;
    rate: string | null;
    rateType: string | null;
    fixedAnnualRate: string | null;
    purchaseDate: string | null;
    dueDate: string | null;
    issueDate: string | null;
    gracePeriodDate: string | null;
    metadata: unknown;
    status: string | null;
    updatedAt: string;
    transactions: Array<{
      id: string;
      description: string | null;
      type: string;
      movementType: string | null;
      quantity: string | null;
      value: string | null;
      amount: string | null;
      netAmount: string | null;
      agreedRate: string | null;
      brokerageNumber: string | null;
      date: string;
      tradeDate: string | null;
      expenses: unknown;
    }>;
    suggestedInstrumentType: InstrumentTypeKey | null;
    suggestedInvestmentClass: InvestmentClassKey | null;
    suggestedFamilyCode: string | null;
    suggestedIndexation: FixedIncomeIndexationKey | null;
    reviewReason: string | null;
  }>;
};

export type DiagramQuestionDto = {
  id: string;
  type: "CERRADO" | "REAL_ESTATE";
  criterion: string;
  text: string;
  active: boolean;
  isDefault: boolean;
  sortOrder: number;
};

export type SimulationDto = {
  id: string;
  requestedAmount: string;
  unallocatedAmount: string;
  suggestions: Array<{
    id: string;
    assetId: string;
    ticker: string;
    name: string;
    investmentClass: InvestmentClassKey;
    instrumentType: InstrumentTypeKey;
    quantity: string;
    value: string;
    suggestionPercentage: string;
    totalAfterSuggestionPercentage: string;
      executed: boolean;
      executionStatus: "PENDING" | "AWAITING_SYNC" | "EXECUTED";
  }>;
};
